mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.example.combinerabbit.mapper
logging:
  config: classpath:log4j2-spring.xml
spring:
  datasource:
    primary:
      url: jdbc:mysql://127.0.0.1:3306/shirotest?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: root

      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 6
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
    second:
      url: jdbc:mysql://127.0.0.1:3306/testone?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: root

      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 6
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
  mvc:
    view:
      prefix: classpath*:templates/views
      suffix: .html
#  mail:
#    port: 25
#    protocol: smtp
#    host: smtp.chengmail.cn
#    username: pywang@dhlk-tech.com
#    password: wangpeiyuan12345!
#    default-encoding: utf-8
#    properties:
#      mail.smtp.auth: true
#      mail.smtp.timeout: 25000
#
#
