spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shirotest
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      initial-size: 5
      min-idle: 5
      max-wait-millis: 6000
      max-idle: 20
      validation-query: select 1 from dual
  mvc:
    view:
      prefix: classpath:templates/views
      suffix: .html
  mail:
    port: 25
    protocol: smtp
    host: smtp.chengmail.cn
    username: pywang@dhlk-tech.com
    password: wangpeiyuan12345!
    default-encoding: utf-8
    properties:
      mail.smtp.auth: true
      mail.smtp.timeout: 25000
  aop:
    proxy-target-class: true

mybatis:
  mapper-locations: mapper/*Mapper.xml
