spring:
  datasource:

    primary:
      jdbc-url: jdbc:mysql://localhost:3306/ts
      username: root
      password: root

    second:
      jdbc-url: jdbc:mysql://localhost:3306/test
      username: root
      password: root



  mvc:
    view:
      prefix: classpath:templates/views
      suffix: .html
  mail:
    port: 25
    protocol: smtp
    host: smtp.chengmail.cn
    username: pywang@dhlk-tech.com
    password: wangpeiyuan12345!
    default-encoding: utf-8
    properties:
      mail.smtp.auth: true
      mail.smtp.timeout: 25000
  aop:
    proxy-target-class: true

mybatis:
  mapper-locations: mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  config: classpath:log4j2-spring.xml