server:
  port: 8763

spring:
  application:
    name: service-hi

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'
      cors:
        allowed-origins: '*'
        allowed-methods: '*'
  endpoint:
    health:
      show-details: always
  port: 4567
  security:
    enabled: false

hystrix:
  metrics:
    polling-interval-ms: 2000
    enabled: true
  command:
    default:
      execution:
        isolation:
          semaphore:
            maxConcurrentRequests: 450
mybatis:
  configuration:
    map-underscore-to-camel-case: true



