eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8765
spring:
  application:
    name: service-ribbon
  cloud:
    loadbalancer:
      retry:
        enabled: true
ribbon:
  eager-load:
    enabled: true

